<?xml version="1.0"?>
<PanoExperiment xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <_UID>ba83eeac-db7f-448c-86e4-8b2addcb1320</_UID>
  <Version>PanoObjects.dll Version 1.0.0.1</Version>
  <UID>ba83eeac-db7f-448c-86e4-8b2addcb1320</UID>
  <Name>LTA_b</Name>
  <Enable>false</Enable>
  <Visible>false</Visible>
  <IsDeletable>true</IsDeletable>
  <IsReadOny>false</IsReadOny>
  <IconRelativePathName>
    <uriKind>eRelativeDataPath</uriKind>
    <RelativePathName>\tempExperiment.jpg</RelativePathName>
  </IconRelativePathName>
  <X>0</X>
  <Y>0</Y>
  <Z>0</Z>
  <Roll>0</Roll>
  <Yaw>0</Yaw>
  <Pitch>0</Pitch>
  <Children>
    <PanoCategory>
      <_UID>2db8fadb-ea1f-412e-8df9-76c2287cc5f1</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>2db8fadb-ea1f-412e-8df9-76c2287cc5f1</UID>
      <Name>Field</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Field.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoField>
          <_UID>ef5129d7-ce61-47e8-90ba-6c6e7d98ff00</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>ef5129d7-ce61-47e8-90ba-6c6e7d98ff00</UID>
          <Name>8_Style Urban Expressway</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\8_Style Urban Expressway\8_Style Urban Expressway.jpg</RelativePathName>
          </IconRelativePathName>
          <UnityObjectRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\8_Style Urban Expressway</RelativePathName>
          </UnityObjectRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <Cracks>0</Cracks>
          <Dirtiness>0.3</Dirtiness>
          <Opacity>1</Opacity>
          <Snowpack>0</Snowpack>
          <Summary>  One end is a 125m radius arc, the other end
is a 250m radius arc, and the middle is an 
intersection with two-way four-lane. The 
transition of arc and straight should meet the
requirements of the speed of 72km/h (namely 20m/s),
and at least 100m arc is required. The arc with 
a radius of 125m (about 375m) meets the requirements,
but the intersection with the straight line needs
a helical transition.
</Summary>
          <Wetness>0</Wetness>
          <Classify>Urban</Classify>
        </PanoField>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>3da15bff-abf7-4630-87f5-ee4cc2905a0c</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>3da15bff-abf7-4630-87f5-ee4cc2905a0c</UID>
      <Name>Vehicles</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Vehicles.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoTestVehicle>
          <_UID>4e1bf311-cfd7-4dc5-9737-8f993466f60d</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>4e1bf311-cfd7-4dc5-9737-8f993466f60d</UID>
          <Name>Veh_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>-7.6656570434570313</X>
          <Y>-12.100637435913086</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>44.957949880944163</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>8d0eb415-30fb-4a91-935b-4160b45e06fc</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>8d0eb415-30fb-4a91-935b-4160b45e06fc</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>4e1bf311-cfd7-4dc5-9737-8f993466f60d</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <Guid>3536357b-4b04-48aa-9425-9ad49913ebea</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>4e1bf311-cfd7-4dc5-9737-8f993466f60d</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>10</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>10</InitSpeed>
            <HasNone>true</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>4e1bf311-cfd7-4dc5-9737-8f993466f60d</Name>
              <Owner />
              <ObservableName>Veh_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos>
                <int>2</int>
                <int>14</int>
                <int>22</int>
              </TrajectoryKeyInTrajectoryPos>
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-7.665657</X>
                  <Y>-12.1006374</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-6.82885027</X>
                  <Y>-11.2626019</Y>
                  <Z>0.162</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-5.9920435</X>
                  <Y>-10.4245663</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-4.9945507</X>
                  <Y>-9.092835</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-3.997058</X>
                  <Y>-7.76110458</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-2.002072</X>
                  <Y>-5.09764242</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.66934133</X>
                  <Y>-3.76610422</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.33661044</X>
                  <Y>-2.43456626</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-0.671148837</X>
                  <Y>0.228509977</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.00318</X>
                  <Y>1.55985522</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.33521128</X>
                  <Y>2.89120054</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.99927366</X>
                  <Y>5.553891</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-2.996067</X>
                  <Y>6.88504362</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-3.99286032</X>
                  <Y>8.216196</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-5.986447</X>
                  <Y>10.8785009</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-7.29758739</X>
                  <Y>12.1914978</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-8.608728</X>
                  <Y>13.5044937</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-11.2310095</X>
                  <Y>16.1304874</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-16.4755726</X>
                  <Y>21.3824749</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-26.9646969</X>
                  <Y>31.88645</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-47.9429474</X>
                  <Y>52.8943977</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-89.8994446</X>
                  <Y>94.91029</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-173.812439</X>
                  <Y>178.9421</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-5.9920435</X>
                  <Y>-10.4245663</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-5.986447</X>
                  <Y>10.8785009</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-173.812439</X>
                  <Y>178.9421</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </TrajectoryKeyPoints>
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>97a888eb-47cf-4053-a40f-a0f1d2a4061d</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>97a888eb-47cf-4053-a40f-a0f1d2a4061d</UID>
          <Name>Veh_2</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_2_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>10.302023887634277</X>
          <Y>18.952489852905273</Y>
          <Z>0.343</Z>
          <Roll>0</Roll>
          <Yaw>225.02267330324034</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>22875442-1d9b-42e7-a6c5-9a15ff706ab1</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>22875442-1d9b-42e7-a6c5-9a15ff706ab1</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>97a888eb-47cf-4053-a40f-a0f1d2a4061d</Name>
            <Owner />
            <ObservableName>Veh_2</ObservableName>
            <Guid>be54f50c-7f69-416b-94c7-aa6e38a7c3a5</Guid>
            <Unity_Resource>Vehicle/Car2</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>97a888eb-47cf-4053-a40f-a0f1d2a4061d</Name>
            <Owner />
            <ObservableName>Veh_2</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>10</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>10</InitSpeed>
            <HasNone>true</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>97a888eb-47cf-4053-a40f-a0f1d2a4061d</Name>
              <Owner />
              <ObservableName>Veh_2</ObservableName>
              <TrajectoryKeyInTrajectoryPos>
                <int>3</int>
                <int>8</int>
                <int>15</int>
              </TrajectoryKeyInTrajectoryPos>
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>10.3020239</X>
                  <Y>18.95249</Y>
                  <Z>0.343</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>8.926085</X>
                  <Y>17.57764</Y>
                  <Z>0.25725</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>7.550147</X>
                  <Y>16.20279</Y>
                  <Z>0.1715</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>4.7982707</X>
                  <Y>13.4530907</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>3.71478</X>
                  <Y>12.3692331</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>2.63128948</X>
                  <Y>11.2853756</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>0.464308143</X>
                  <Y>9.11766052</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-3.86965442</X>
                  <Y>4.78223038</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-12.53758</X>
                  <Y>-3.88863039</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-13.8885822</X>
                  <Y>-5.241617</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-15.239584</X>
                  <Y>-6.59460354</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-17.9415874</X>
                  <Y>-9.300576</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-23.3455963</X>
                  <Y>-14.7125225</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-34.153614</X>
                  <Y>-25.5364151</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-55.7696457</X>
                  <Y>-47.1842</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-99.00171</X>
                  <Y>-90.47977</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>4.7982707</X>
                  <Y>13.4530907</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-12.53758</X>
                  <Y>-3.88863039</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-99.00171</X>
                  <Y>-90.47977</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </TrajectoryKeyPoints>
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.343</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Experiment\Vehicle\Veh_2.veh</VehiclePath30>
          <CarResource>Vehicle/Car2</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>c5856b7f-a77d-4809-8c1d-483fb6a14fa0</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>c5856b7f-a77d-4809-8c1d-483fb6a14fa0</UID>
          <Name>Veh_3</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\BoxTruck_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>9.3450098037719727</X>
          <Y>12.836394309997559</Y>
          <Z>0.362</Z>
          <Roll>0</Roll>
          <Yaw>225.02267330324034</Yaw>
          <Pitch>0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>5b877987-4886-4f31-ab5a-685279d7ddb6</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>5b877987-4886-4f31-ab5a-685279d7ddb6</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>c5856b7f-a77d-4809-8c1d-483fb6a14fa0</Name>
            <Owner />
            <ObservableName>Veh_3</ObservableName>
            <Guid>75f6c7d4-c9e1-4b13-b3ad-504ae49e0e33</Guid>
            <Unity_Resource>Vehicle/Truck</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>c5856b7f-a77d-4809-8c1d-483fb6a14fa0</Name>
            <Owner />
            <ObservableName>Veh_3</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>10</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>10</InitSpeed>
            <HasNone>true</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>c5856b7f-a77d-4809-8c1d-483fb6a14fa0</Name>
              <Owner />
              <ObservableName>Veh_3</ObservableName>
              <TrajectoryKeyInTrajectoryPos>
                <int>2</int>
                <int>7</int>
                <int>14</int>
              </TrajectoryKeyInTrajectoryPos>
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>9.34501</X>
                  <Y>12.8363943</Y>
                  <Z>0.362</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>8.361599</X>
                  <Y>11.8537617</Y>
                  <Z>0.181</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>7.378189</X>
                  <Y>10.87113</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>6.294881</X>
                  <Y>9.787455</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>5.211572</X>
                  <Y>8.703779</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>3.04495525</X>
                  <Y>6.53642845</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-1.28827858</X>
                  <Y>2.20172739</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-9.954746</X>
                  <Y>-6.467675</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-11.305748</X>
                  <Y>-7.820662</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-12.6567507</X>
                  <Y>-9.173649</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-15.3587551</X>
                  <Y>-11.8796215</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-20.762764</X>
                  <Y>-17.2915668</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-31.57078</X>
                  <Y>-28.11546</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-53.1868134</X>
                  <Y>-49.7632446</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-96.41888</X>
                  <Y>-93.058815</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>7.378189</X>
                  <Y>10.87113</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-9.954746</X>
                  <Y>-6.467675</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-96.41888</X>
                  <Y>-93.058815</Y>
                  <Z>0</Z>
                </TrajectoryPoint>
              </TrajectoryKeyPoints>
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.362</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>E:\SVN_branches\PanoSim4\Branch\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Experiment\Vehicle\Veh_3.veh</VehiclePath30>
          <CarResource>Vehicle/Truck</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>1ca82ab4-2898-40ed-b38c-27de204210ff</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>1ca82ab4-2898-40ed-b38c-27de204210ff</UID>
          <Name>Veh_1_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>E:\V2X_FAW\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>21.241176605224609</X>
          <Y>-11.218234062194824</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>135.03354766122845</Yaw>
          <Pitch>-0</Pitch>
          <Children />
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>1ca82ab4-2898-40ed-b38c-27de204210ff</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <Guid>429bbd43-13c3-424d-99d2-db13a95dabd6</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>1ca82ab4-2898-40ed-b38c-27de204210ff</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>0</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>0</InitSpeed>
            <HasNone>false</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>1ca82ab4-2898-40ed-b38c-27de204210ff</Name>
              <Owner />
              <ObservableName>Veh_1_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>21.2411766</X>
                  <Y>-11.2182341</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>E:\V2X_FAW\Bin\PanoSim4.1_V2X_FAW\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>180</HeadingAngleOffset>
        </PanoTestVehicle>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>bda92428-92e7-4d80-8a7d-22836da57e9e</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>bda92428-92e7-4d80-8a7d-22836da57e9e</UID>
      <Name>Traffic</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Traffic.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoStochasticTraffic>
          <_UID>1339a3ae-0c22-4a90-84d0-1fb3363b7775</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>1339a3ae-0c22-4a90-84d0-1fb3363b7775</UID>
          <Name>Normal</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\StochasticTraffic.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <ExpDir />
          <TrafficDensity>0.5</TrafficDensity>
          <TrafficEnable>false</TrafficEnable>
          <StepLength>0.05</StepLength>
          <TrafficVehicles />
          <Cautious>0</Cautious>
          <Common>0</Common>
          <Radical>0</Radical>
          <Car>0</Car>
          <Truck>0</Truck>
          <Bus>0</Bus>
          <CarStartSpeed>0</CarStartSpeed>
          <CarMaxSpeed>0</CarMaxSpeed>
          <TruckStartSpeed>0</TruckStartSpeed>
          <TruckMaxSpeed>0</TruckMaxSpeed>
          <BusStartSpeed>0</BusStartSpeed>
          <BusMaxSpeed>0</BusMaxSpeed>
        </PanoStochasticTraffic>
        <PanoCategory>
          <_UID>243d7d48-e1a7-4226-8112-d3b6e077bdb7</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>243d7d48-e1a7-4226-8112-d3b6e077bdb7</UID>
          <Name>Interfering Vehicles</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Interfering Vehicles.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoDisturbance>
          <_UID>65eedf42-916b-44d7-9d33-73f9769d019a</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>65eedf42-916b-44d7-9d33-73f9769d019a</UID>
          <Name>Disturbance</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Disturbance.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <DisturbanceEnable>false</DisturbanceEnable>
          <DisturbanceModel>Cut-In</DisturbanceModel>
          <CutInDisturbanceStartsCondition>AtTime</CutInDisturbanceStartsCondition>
          <CutInAtTimeValue>10</CutInAtTimeValue>
          <CutInAtStationValue>10</CutInAtStationValue>
          <CutInAtSpeedValue>10</CutInAtSpeedValue>
          <CutInAtDistanceValue>10</CutInAtDistanceValue>
          <CutInDisturbanceLaneInit>LeftLane</CutInDisturbanceLaneInit>
          <CutInSpeedValue>10</CutInSpeedValue>
          <CutInAngleValue>10</CutInAngleValue>
          <CutInDisturbingObject>Sedan</CutInDisturbingObject>
          <CutInDisturbingObjectUnityResource>Vehicle/Car1</CutInDisturbingObjectUnityResource>
          <SpeedVariationDisturbanceStartsCondition>AtTime</SpeedVariationDisturbanceStartsCondition>
          <SpeedVariationAtTimeValue>10</SpeedVariationAtTimeValue>
          <SpeedVariationAtStationValue>10</SpeedVariationAtStationValue>
          <SpeedVariationAtSpeedValue>10</SpeedVariationAtSpeedValue>
          <SpeedVariationAtDistanceValue>10</SpeedVariationAtDistanceValue>
          <SpeedVariationSideDistanceValue>0</SpeedVariationSideDistanceValue>
          <SpeedVariationDisturbingObject>Sedan</SpeedVariationDisturbingObject>
          <SpeedVariationDisturbingObjectUnityResource>Vehicle/Car1</SpeedVariationDisturbingObjectUnityResource>
          <SpeedVariationTimeArray />
          <SpeedVariationSpeedArray />
          <PedestrianCrossingDisturbanceStartsCondition>AtTime</PedestrianCrossingDisturbanceStartsCondition>
          <PedestrianCrossingAtTimeValue>10</PedestrianCrossingAtTimeValue>
          <PedestrianCrossingAtStationValue>10</PedestrianCrossingAtStationValue>
          <PedestrianCrossingAtSpeedValue>10</PedestrianCrossingAtSpeedValue>
          <PedestrianCrossingAtFrontDistanceValue>10</PedestrianCrossingAtFrontDistanceValue>
          <PedestrianCrossingAtSideDistanceValue>1</PedestrianCrossingAtSideDistanceValue>
          <PedestrianCrossingCrossAngleValue>0</PedestrianCrossingCrossAngleValue>
          <PedestrianCrossingEnsureCollision>false</PedestrianCrossingEnsureCollision>
          <PedestrianCrossingDisturbingObject>Boywalk</PedestrianCrossingDisturbingObject>
          <PedestrianCrossingDisturbingObjectUnityResource>People/Boywalk</PedestrianCrossingDisturbingObjectUnityResource>
          <PedestrianCrossingTimeArray>
            <double>0</double>
            <double>10</double>
          </PedestrianCrossingTimeArray>
          <PedestrianCrossingSpeedArray>
            <double>5.4</double>
            <double>5.4</double>
          </PedestrianCrossingSpeedArray>
        </PanoDisturbance>
        <PanoCategory>
          <_UID>3bd7fa1e-77d0-448b-b3ed-e2fe5e4a2f7a</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>3bd7fa1e-77d0-448b-b3ed-e2fe5e4a2f7a</UID>
          <Name>Pedestrian</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Pedestrian.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>5883875e-d73a-4856-a18f-1c6b1f589f32</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>5883875e-d73a-4856-a18f-1c6b1f589f32</UID>
          <Name>AuxiliarySign</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\AuxiliarySign.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather>
      <_UID>96b96809-5e11-4d51-a016-3ac9b6fd5fb3</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>96b96809-5e11-4d51-a016-3ac9b6fd5fb3</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <WeatherTypeData>Sunny</WeatherTypeData>
      <wt_TimeOfDay>0.375</wt_TimeOfDay>
      <wt_CloudsValue>0.6</wt_CloudsValue>
      <wt_RainValue>0</wt_RainValue>
      <wt_SnowValue>0</wt_SnowValue>
      <wt_FogValue>0</wt_FogValue>
      <wt_Wetness>0</wt_Wetness>
      <wt_Snowness>0</wt_Snowness>
      <wt_Cracks>0</wt_Cracks>
      <wt_Dirtiness>0</wt_Dirtiness>
      <wt_Opacity>0</wt_Opacity>
    </PanoWeather>
    <PanoCategory>
      <_UID>2be2d9cb-0a75-4805-ba0b-664ae7c5da0c</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>2be2d9cb-0a75-4805-ba0b-664ae7c5da0c</UID>
      <Name>StaticOjbects</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\StaticOjbects.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoCategory>
          <_UID>8f8f2a6d-a66c-4c7e-8ba0-83f7f0b2c372</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>8f8f2a6d-a66c-4c7e-8ba0-83f7f0b2c372</UID>
          <Name>Traffic Signs</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Traffic Signs.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>07d0f799-462b-4206-adb0-129db1728204</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>07d0f799-462b-4206-adb0-129db1728204</UID>
          <Name>Facilities</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Facilities.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>2a01dd95-f31e-485d-bc2a-21e6693ae19f</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>2a01dd95-f31e-485d-bc2a-21e6693ae19f</UID>
          <Name>Buildings</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Buildings.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>89dbb3a2-39ed-4bb4-acec-af030bd81e9f</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>89dbb3a2-39ed-4bb4-acec-af030bd81e9f</UID>
          <Name>Vegetations</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Vegetations.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather2>
      <_UID>4f5fd055-27a3-4dfa-b016-4fab3f0aa2a2</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>4f5fd055-27a3-4dfa-b016-4fab3f0aa2a2</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather2.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <_weatherContext>
        <WeatherType>Sunny</WeatherType>
        <RainyType>None</RainyType>
        <SnowyTypes>None</SnowyTypes>
        <FogVisibility>300</FogVisibility>
        <TimeOfDay>9</TimeOfDay>
        <LightPoles>true</LightPoles>
        <Cloudiness>0.5</Cloudiness>
      </_weatherContext>
      <WeatherType>Sunny</WeatherType>
      <RainyType>None</RainyType>
      <SnowyType>None</SnowyType>
      <FogVisibility>300</FogVisibility>
      <TimeOfDay>9</TimeOfDay>
      <LightPoles>true</LightPoles>
      <Cloudiness>0.5</Cloudiness>
    </PanoWeather2>
    <PanoV2X>
      <_UID>7c16152a-e0d9-4458-9dba-f25e26ca0aa5</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>7c16152a-e0d9-4458-9dba-f25e26ca0aa5</UID>
      <Name>V2X</Name>
      <Enable>false</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\V2X.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Data>
        <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
        <Name>7c16152a-e0d9-4458-9dba-f25e26ca0aa5</Name>
        <Owner />
        <ObservableName>V2X</ObservableName>
        <NetModel>Ideal_Model</NetModel>
        <Scenario>HighWay</Scenario>
        <CommunicationRadius>500</CommunicationRadius>
        <DeliveryRatio>0.5</DeliveryRatio>
        <AverageDelay>50</AverageDelay>
        <PercentageInTraffic>100</PercentageInTraffic>
        <V2XParticipants>
          <SerializableDictionary>
            <key>
              <string>TrafficLight</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>IndicationSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>WarningSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>ForbiddenSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>HighwaySign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Facilities</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>SUMOVehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Vehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
        </V2XParticipants>
      </Data>
      <OBUModel>Ideal_Model</OBUModel>
      <Scenario>HighWay</Scenario>
      <CommunicationRadius>500</CommunicationRadius>
      <DeliveryRatio>0.5</DeliveryRatio>
      <AverageDelay>50</AverageDelay>
      <PercentageInTraffic>100</PercentageInTraffic>
    </PanoV2X>
  </Children>
  <StopTime>500</StopTime>
  <StartTime>0</StartTime>
  <ExpDir>D:\NewPanoSimData\Experiment\LTA_b</ExpDir>
  <IsLinkToOtherExpModel>false</IsLinkToOtherExpModel>
  <MDLFullPath />
  <MDLDirectory />
  <MDLExpName />
  <NeedBuild>false</NeedBuild>
  <NeedDownload>false</NeedDownload>
</PanoExperiment>