<?xml version="1.0"?>
<PanoExperiment xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <_UID>e57811b2-2086-4aa6-92dd-052cc43c1528</_UID>
  <Version>PanoObjects.dll Version 1.0.0.1</Version>
  <UID>e57811b2-2086-4aa6-92dd-052cc43c1528</UID>
  <Name>ICW_a</Name>
  <Enable>false</Enable>
  <Visible>false</Visible>
  <IsDeletable>true</IsDeletable>
  <IsReadOny>false</IsReadOny>
  <IconRelativePathName>
    <uriKind>eRelativeDataPath</uriKind>
    <RelativePathName>\tempExperiment.jpg</RelativePathName>
  </IconRelativePathName>
  <X>0</X>
  <Y>0</Y>
  <Z>0</Z>
  <Roll>0</Roll>
  <Yaw>0</Yaw>
  <Pitch>0</Pitch>
  <Children>
    <PanoCategory>
      <_UID>3a64e384-444b-4f46-a798-4aa9419774a4</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>3a64e384-444b-4f46-a798-4aa9419774a4</UID>
      <Name>Field</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Field.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoField>
          <_UID>1f15d4d1-d0c7-4644-bc5a-e43c37355add</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>1f15d4d1-d0c7-4644-bc5a-e43c37355add</UID>
          <Name>DownTown</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\DownTown\DownTown.jpg</RelativePathName>
          </IconRelativePathName>
          <UnityObjectRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\DownTown</RelativePathName>
          </UnityObjectRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <Cracks>0</Cracks>
          <Dirtiness>0.3</Dirtiness>
          <Opacity>1</Opacity>
          <Snowpack>0</Snowpack>
          <Summary>  The total length of the road is 5900 meters, including radius 
125m arc (about 470m), 250m arc (about 760m), five intersections,
two-way six-lane and auxiliary four-lane (including double 
yellow solid line, single yellow solid line, single white solid
line, white dotted line, yellow dotted line, single blue solid
line and road signs), and the lane width is 3.5 meters.
</Summary>
          <Wetness>0</Wetness>
          <Classify>Urban</Classify>
        </PanoField>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>df516248-76f5-41c2-8b58-d47155dde720</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>df516248-76f5-41c2-8b58-d47155dde720</UID>
      <Name>Vehicles</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Vehicles.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoTestVehicle>
          <_UID>7a840300-6a2b-4f34-9d95-831f7d6ae28e</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>7a840300-6a2b-4f34-9d95-831f7d6ae28e</UID>
          <Name>Veh_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>-45.875</X>
          <Y>242.24510192871094</Y>
          <Z>0.324</Z>
          <Roll>-0</Roll>
          <Yaw>359.99999923515151</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>8d0a7c5c-a144-4320-8e3b-f3293dec8fd6</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>8d0a7c5c-a144-4320-8e3b-f3293dec8fd6</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>7a840300-6a2b-4f34-9d95-831f7d6ae28e</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <Guid>1fee1aca-b9c5-416b-97c9-09c66d1e8eb6</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>7a840300-6a2b-4f34-9d95-831f7d6ae28e</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>15</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>15</InitSpeed>
            <HasNone>false</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>15</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>7a840300-6a2b-4f34-9d95-831f7d6ae28e</Name>
              <Owner />
              <ObservableName>Veh_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-45.875</X>
                  <Y>242.2451</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>b7d0cac6-2e70-43e3-a322-7c7b3e2b0354</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>b7d0cac6-2e70-43e3-a322-7c7b3e2b0354</UID>
          <Name>Veh_1_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>-95.199005126953125</X>
          <Y>268.4091796875</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>90</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>bf7f61a6-ac52-4306-87ab-2fd43ac63d10</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>bf7f61a6-ac52-4306-87ab-2fd43ac63d10</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>b7d0cac6-2e70-43e3-a322-7c7b3e2b0354</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <Guid>857896f9-443d-4cdd-ae8e-40a2c09c0fbf</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>b7d0cac6-2e70-43e3-a322-7c7b3e2b0354</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>27</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>27</InitSpeed>
            <HasNone>false</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>27</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>b7d0cac6-2e70-43e3-a322-7c7b3e2b0354</Name>
              <Owner />
              <ObservableName>Veh_1_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-95.1990051</X>
                  <Y>268.40918</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>d84d7fde-53e6-4f2b-9c8e-847f55afb80f</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>d84d7fde-53e6-4f2b-9c8e-847f55afb80f</UID>
          <Name>Veh_1_2</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>-75.199005126953125</X>
          <Y>265.07501220703125</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>90</Yaw>
          <Pitch>-0</Pitch>
          <Children />
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>d84d7fde-53e6-4f2b-9c8e-847f55afb80f</Name>
            <Owner />
            <ObservableName>Veh_1_2</ObservableName>
            <Guid>6688cd32-a5dc-45a2-af00-729d2a4b3c32</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>d84d7fde-53e6-4f2b-9c8e-847f55afb80f</Name>
            <Owner />
            <ObservableName>Veh_1_2</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>15</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>15</InitSpeed>
            <HasNone>false</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>15</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>d84d7fde-53e6-4f2b-9c8e-847f55afb80f</Name>
              <Owner />
              <ObservableName>Veh_1_2</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>-75.1990051</X>
                  <Y>265.075</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>50506598-1e55-448c-aa04-f987fed9808e</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>50506598-1e55-448c-aa04-f987fed9808e</UID>
      <Name>Traffic</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Traffic.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoStochasticTraffic>
          <_UID>15ce407a-1171-48cb-b95e-6ac5fc1b2b9e</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>15ce407a-1171-48cb-b95e-6ac5fc1b2b9e</UID>
          <Name>Normal</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\StochasticTraffic.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <ExpDir />
          <TrafficDensity>0.5</TrafficDensity>
          <TrafficEnable>false</TrafficEnable>
          <StepLength>0.05</StepLength>
          <TrafficVehicles />
          <Cautious>0</Cautious>
          <Common>0</Common>
          <Radical>0</Radical>
          <Car>0</Car>
          <Truck>0</Truck>
          <Bus>0</Bus>
          <CarStartSpeed>0</CarStartSpeed>
          <CarMaxSpeed>0</CarMaxSpeed>
          <TruckStartSpeed>0</TruckStartSpeed>
          <TruckMaxSpeed>0</TruckMaxSpeed>
          <BusStartSpeed>0</BusStartSpeed>
          <BusMaxSpeed>0</BusMaxSpeed>
        </PanoStochasticTraffic>
        <PanoCategory>
          <_UID>5baf589a-77e0-4c46-a9cf-4fc893d82f35</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>5baf589a-77e0-4c46-a9cf-4fc893d82f35</UID>
          <Name>Interfering Vehicles</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Interfering Vehicles.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoDisturbance>
          <_UID>0ba4a824-a0c4-4c68-bbe0-e450bc384078</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>0ba4a824-a0c4-4c68-bbe0-e450bc384078</UID>
          <Name>Disturbance</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Disturbance.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <DisturbanceEnable>false</DisturbanceEnable>
          <DisturbanceModel>Cut-In</DisturbanceModel>
          <CutInDisturbanceStartsCondition>AtTime</CutInDisturbanceStartsCondition>
          <CutInAtTimeValue>10</CutInAtTimeValue>
          <CutInAtStationValue>10</CutInAtStationValue>
          <CutInAtSpeedValue>10</CutInAtSpeedValue>
          <CutInAtDistanceValue>10</CutInAtDistanceValue>
          <CutInDisturbanceLaneInit>LeftLane</CutInDisturbanceLaneInit>
          <CutInSpeedValue>10</CutInSpeedValue>
          <CutInAngleValue>10</CutInAngleValue>
          <CutInDisturbingObject>Sedan</CutInDisturbingObject>
          <CutInDisturbingObjectUnityResource>Vehicle/Car1</CutInDisturbingObjectUnityResource>
          <SpeedVariationDisturbanceStartsCondition>AtTime</SpeedVariationDisturbanceStartsCondition>
          <SpeedVariationAtTimeValue>10</SpeedVariationAtTimeValue>
          <SpeedVariationAtStationValue>10</SpeedVariationAtStationValue>
          <SpeedVariationAtSpeedValue>10</SpeedVariationAtSpeedValue>
          <SpeedVariationAtDistanceValue>10</SpeedVariationAtDistanceValue>
          <SpeedVariationSideDistanceValue>0</SpeedVariationSideDistanceValue>
          <SpeedVariationDisturbingObject>Sedan</SpeedVariationDisturbingObject>
          <SpeedVariationDisturbingObjectUnityResource>Vehicle/Car1</SpeedVariationDisturbingObjectUnityResource>
          <SpeedVariationTimeArray />
          <SpeedVariationSpeedArray />
          <PedestrianCrossingDisturbanceStartsCondition>AtTime</PedestrianCrossingDisturbanceStartsCondition>
          <PedestrianCrossingAtTimeValue>10</PedestrianCrossingAtTimeValue>
          <PedestrianCrossingAtStationValue>10</PedestrianCrossingAtStationValue>
          <PedestrianCrossingAtSpeedValue>10</PedestrianCrossingAtSpeedValue>
          <PedestrianCrossingAtFrontDistanceValue>10</PedestrianCrossingAtFrontDistanceValue>
          <PedestrianCrossingAtSideDistanceValue>1</PedestrianCrossingAtSideDistanceValue>
          <PedestrianCrossingCrossAngleValue>0</PedestrianCrossingCrossAngleValue>
          <PedestrianCrossingEnsureCollision>false</PedestrianCrossingEnsureCollision>
          <PedestrianCrossingDisturbingObject>Boywalk</PedestrianCrossingDisturbingObject>
          <PedestrianCrossingDisturbingObjectUnityResource>People/Boywalk</PedestrianCrossingDisturbingObjectUnityResource>
          <PedestrianCrossingTimeArray>
            <double>0</double>
            <double>10</double>
          </PedestrianCrossingTimeArray>
          <PedestrianCrossingSpeedArray>
            <double>5.4</double>
            <double>5.4</double>
          </PedestrianCrossingSpeedArray>
        </PanoDisturbance>
        <PanoCategory>
          <_UID>772604e3-32b8-4fec-9c0c-126854cbca7c</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>772604e3-32b8-4fec-9c0c-126854cbca7c</UID>
          <Name>Pedestrian</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Pedestrian.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>4d115cb8-69a3-456d-ba3b-cf1d7ce96083</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>4d115cb8-69a3-456d-ba3b-cf1d7ce96083</UID>
          <Name>AuxiliarySign</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\AuxiliarySign.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather>
      <_UID>21786bda-4549-4f71-b250-934ea6970906</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>21786bda-4549-4f71-b250-934ea6970906</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <WeatherTypeData>Sunny</WeatherTypeData>
      <wt_TimeOfDay>0.375</wt_TimeOfDay>
      <wt_CloudsValue>0.6</wt_CloudsValue>
      <wt_RainValue>0</wt_RainValue>
      <wt_SnowValue>0</wt_SnowValue>
      <wt_FogValue>0</wt_FogValue>
      <wt_Wetness>0</wt_Wetness>
      <wt_Snowness>0</wt_Snowness>
      <wt_Cracks>0</wt_Cracks>
      <wt_Dirtiness>0</wt_Dirtiness>
      <wt_Opacity>0</wt_Opacity>
    </PanoWeather>
    <PanoCategory>
      <_UID>106a97b7-09ec-4007-b87f-70be0bca7a0f</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>106a97b7-09ec-4007-b87f-70be0bca7a0f</UID>
      <Name>StaticOjbects</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\StaticOjbects.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoCategory>
          <_UID>0bb3a88c-baee-45fd-a7b7-e1169dc16224</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>0bb3a88c-baee-45fd-a7b7-e1169dc16224</UID>
          <Name>Traffic Signs</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Traffic Signs.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>46e1ee9d-6844-4759-afc5-0c67dde3efa5</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>46e1ee9d-6844-4759-afc5-0c67dde3efa5</UID>
          <Name>Facilities</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Facilities.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>57530464-773e-4e16-97b5-2f330534334c</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>57530464-773e-4e16-97b5-2f330534334c</UID>
          <Name>Buildings</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Buildings.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>a49522c0-5440-4b55-bfc7-c09c71d5d7cb</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>a49522c0-5440-4b55-bfc7-c09c71d5d7cb</UID>
          <Name>Vegetations</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Vegetations.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather2>
      <_UID>e757faa7-f76f-4d83-8ee5-4fb9033e4f34</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>e757faa7-f76f-4d83-8ee5-4fb9033e4f34</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather2.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <_weatherContext>
        <WeatherType>Sunny</WeatherType>
        <RainyType>None</RainyType>
        <SnowyTypes>None</SnowyTypes>
        <FogVisibility>300</FogVisibility>
        <TimeOfDay>9</TimeOfDay>
        <LightPoles>true</LightPoles>
        <Cloudiness>0.5</Cloudiness>
      </_weatherContext>
      <WeatherType>Sunny</WeatherType>
      <RainyType>None</RainyType>
      <SnowyType>None</SnowyType>
      <FogVisibility>300</FogVisibility>
      <TimeOfDay>9</TimeOfDay>
      <LightPoles>true</LightPoles>
      <Cloudiness>0.5</Cloudiness>
    </PanoWeather2>
    <PanoV2X>
      <_UID>eb80362f-4fee-4901-ae5c-448599915a28</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>eb80362f-4fee-4901-ae5c-448599915a28</UID>
      <Name>V2X</Name>
      <Enable>false</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\V2X.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Data>
        <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
        <Name>eb80362f-4fee-4901-ae5c-448599915a28</Name>
        <Owner />
        <ObservableName>V2X</ObservableName>
        <NetModel>Ideal_Model</NetModel>
        <Scenario>HighWay</Scenario>
        <CommunicationRadius>500</CommunicationRadius>
        <DeliveryRatio>0.5</DeliveryRatio>
        <AverageDelay>50</AverageDelay>
        <PercentageInTraffic>100</PercentageInTraffic>
        <V2XParticipants>
          <SerializableDictionary>
            <key>
              <string>TrafficLight</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>IndicationSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>WarningSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>ForbiddenSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>HighwaySign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Facilities</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>SUMOVehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Vehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
        </V2XParticipants>
      </Data>
      <OBUModel>Ideal_Model</OBUModel>
      <Scenario>HighWay</Scenario>
      <CommunicationRadius>500</CommunicationRadius>
      <DeliveryRatio>0.5</DeliveryRatio>
      <AverageDelay>50</AverageDelay>
      <PercentageInTraffic>100</PercentageInTraffic>
    </PanoV2X>
  </Children>
  <Summary />
  <StopTime>500</StopTime>
  <StartTime>0</StartTime>
  <ExpDir>D:\NewPanoSimData\Experiment\ICW_a</ExpDir>
  <IsLinkToOtherExpModel>false</IsLinkToOtherExpModel>
  <MDLFullPath />
  <MDLDirectory />
  <MDLExpName />
  <NeedBuild>false</NeedBuild>
  <NeedDownload>false</NeedDownload>
</PanoExperiment>