<?xml version="1.0"?>
<PanoExperiment xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <_UID>58cbb5ed-184e-46bc-b7cb-1fd05e3a2264</_UID>
  <Version>PanoObjects.dll Version 1.0.0.1</Version>
  <UID>58cbb5ed-184e-46bc-b7cb-1fd05e3a2264</UID>
  <Name>DNPW_a</Name>
  <Enable>false</Enable>
  <Visible>false</Visible>
  <IsDeletable>true</IsDeletable>
  <IsReadOny>false</IsReadOny>
  <IconRelativePathName>
    <uriKind>eRelativeDataPath</uriKind>
    <RelativePathName>\tempExperiment.jpg</RelativePathName>
  </IconRelativePathName>
  <X>0</X>
  <Y>0</Y>
  <Z>0</Z>
  <Roll>0</Roll>
  <Yaw>0</Yaw>
  <Pitch>0</Pitch>
  <Children>
    <PanoCategory>
      <_UID>121d643a-c3d4-4a5f-a532-2ce8a377c692</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>121d643a-c3d4-4a5f-a532-2ce8a377c692</UID>
      <Name>Field</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Field.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoField>
          <_UID>294c1c36-5d12-47d3-8d46-01143410ed17</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>294c1c36-5d12-47d3-8d46-01143410ed17</UID>
          <Name>Parking</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\Parking\Parking.jpg</RelativePathName>
          </IconRelativePathName>
          <UnityObjectRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>Fields\Parking</RelativePathName>
          </UnityObjectRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <Cracks>0</Cracks>
          <Dirtiness>0.3</Dirtiness>
          <Opacity>1</Opacity>
          <Snowpack>0</Snowpack>
          <Summary>The total length of the road is 2,189 meters, two-way two-lane
(including white dotted line and road signs), 5 T-junction,
 3 Y-junction, lane width is 4 meters, 18 parking Spaces in 
parking lot 1, 18 parking Spaces in parking lot 2, 24 parking 
Spaces on the side of the square, and 15 parking Spaces in the park.
</Summary>
          <Wetness>0</Wetness>
          <Classify>Urban</Classify>
        </PanoField>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>fec0ce18-1fa0-4c37-86bd-71065a941730</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>fec0ce18-1fa0-4c37-86bd-71065a941730</UID>
      <Name>Vehicles</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Vehicles.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoTestVehicle>
          <_UID>082ae85f-ee67-4336-b16c-9b15ee3e23af</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>082ae85f-ee67-4336-b16c-9b15ee3e23af</UID>
          <Name>Veh_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>94.212066650390625</X>
          <Y>3.7937817573547363</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>270.04404954824554</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>13aa91f8-9d5f-44cf-89f7-c87c6187dc92</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>13aa91f8-9d5f-44cf-89f7-c87c6187dc92</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>082ae85f-ee67-4336-b16c-9b15ee3e23af</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <Guid>773086c1-7e93-4217-bac7-79ccaab26df7</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>082ae85f-ee67-4336-b16c-9b15ee3e23af</Name>
            <Owner />
            <ObservableName>Veh_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>1</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>1</InitSpeed>
            <HasNone>true</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>false</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime2" msdata:rowOrder="1" diffgr:hasChanges="inserted">
                      <Time>1</Time>
                      <Speed>15</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime3" msdata:rowOrder="2" diffgr:hasChanges="inserted">
                      <Time>2</Time>
                      <Speed>20</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime4" msdata:rowOrder="3" diffgr:hasChanges="inserted">
                      <Time>4</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime5" msdata:rowOrder="4" diffgr:hasChanges="inserted">
                      <Time>5</Time>
                      <Speed>5</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime6" msdata:rowOrder="5" diffgr:hasChanges="inserted">
                      <Time>6</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                    <SpeedVsTime diffgr:id="SpeedVsTime7" msdata:rowOrder="6" diffgr:hasChanges="inserted">
                      <Time>7</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>1</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>082ae85f-ee67-4336-b16c-9b15ee3e23af</Name>
              <Owner />
              <ObservableName>Veh_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos>
                <int>4</int>
                <int>7</int>
                <int>10</int>
                <int>16</int>
              </TrajectoryKeyInTrajectoryPos>
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>94.21207</X>
                  <Y>3.79378176</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>92.3700943</X>
                  <Y>3.766957</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>90.52812</X>
                  <Y>3.74013233</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>86.84418</X>
                  <Y>3.686483</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>79.47628</X>
                  <Y>3.579184</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>77.91171</X>
                  <Y>3.21812868</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>76.34714</X>
                  <Y>2.85707355</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>73.2179947</X>
                  <Y>2.134963</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>71.8219147</X>
                  <Y>2.49601841</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>70.42583</X>
                  <Y>2.85707355</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>67.63367</X>
                  <Y>3.579184</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>65.7170639</X>
                  <Y>3.58520174</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>63.8004646</X>
                  <Y>3.59121919</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>59.9672623</X>
                  <Y>3.60325432</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>52.3008537</X>
                  <Y>3.62732482</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>36.96804</X>
                  <Y>3.67546558</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>6.302414</X>
                  <Y>3.77174687</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>79.47628</X>
                  <Y>3.579184</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>73.2179947</X>
                  <Y>2.134963</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>67.63367</X>
                  <Y>3.579184</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>6.302414</X>
                  <Y>3.77174687</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </TrajectoryKeyPoints>
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>26798c5f-2ead-492a-9ecd-9d9d0d86581b</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>26798c5f-2ead-492a-9ecd-9d9d0d86581b</UID>
          <Name>Veh_1_1</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>53.6048469543457</X>
          <Y>0.079454042017459869</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>90.044051077942569</Yaw>
          <Pitch>0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>31eed26a-7b17-4d46-a39e-b605f529d57e</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>31eed26a-7b17-4d46-a39e-b605f529d57e</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>26798c5f-2ead-492a-9ecd-9d9d0d86581b</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <Guid>b3dca1a7-71b1-4788-a386-cb740c4233fc</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>26798c5f-2ead-492a-9ecd-9d9d0d86581b</Name>
            <Owner />
            <ObservableName>Veh_1_1</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>10</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>10</InitSpeed>
            <HasNone>true</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>26798c5f-2ead-492a-9ecd-9d9d0d86581b</Name>
              <Owner />
              <ObservableName>Veh_1_1</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>53.604847</X>
                  <Y>0.07945404</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
        <PanoTestVehicle>
          <_UID>31bf20a0-117a-45ba-8453-edb800b24b17</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>31bf20a0-117a-45ba-8453-edb800b24b17</UID>
          <Name>Veh_1_2</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>true</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eAbsolutePath</uriKind>
            <RelativePathName>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Bin\Resources\ImgVehicle\Sedan_1_P.jpg</RelativePathName>
          </IconRelativePathName>
          <X>79.212074279785156</X>
          <Y>3.805314302444458</Y>
          <Z>0.324</Z>
          <Roll>0</Roll>
          <Yaw>270.04404954824554</Yaw>
          <Pitch>-0</Pitch>
          <Children>
            <PanoV2XOBU>
              <_UID>5e8af0e5-e49f-4269-b64f-5a1f3be31bee</_UID>
              <Version>PanoObjects.dll Version 1.0.0.1</Version>
              <UID>5e8af0e5-e49f-4269-b64f-5a1f3be31bee</UID>
              <Name>OBU</Name>
              <Enable>true</Enable>
              <Visible>true</Visible>
              <IsDeletable>true</IsDeletable>
              <IsReadOny>false</IsReadOny>
              <IconRelativePathName>
                <uriKind>eRelativeDataPath</uriKind>
                <RelativePathName>Sensors\\Cameras\Pinhole\Pinhole.jpg</RelativePathName>
              </IconRelativePathName>
              <X>0</X>
              <Y>0</Y>
              <Z>0</Z>
              <Roll>0</Roll>
              <Yaw>0</Yaw>
              <Pitch>0</Pitch>
              <ShowColor>
                <A>255</A>
                <R>255</R>
                <G>255</G>
                <B>255</B>
                <ScA>1</ScA>
                <ScR>1</ScR>
                <ScG>1</ScG>
                <ScB>1</ScB>
              </ShowColor>
            </PanoV2XOBU>
          </Children>
          <ThreeDData>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>31bf20a0-117a-45ba-8453-edb800b24b17</Name>
            <Owner />
            <ObservableName>Veh_1_2</ObservableName>
            <Guid>5747800a-d2f0-4842-a823-bc2dc97fe3a5</Guid>
            <Unity_Resource>Vehicle/Car1</Unity_Resource>
            <Unity_Type>0</Unity_Type>
          </ThreeDData>
          <DriverControl>
            <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
            <Name>31bf20a0-117a-45ba-8453-edb800b24b17</Name>
            <Owner />
            <ObservableName>Veh_1_2</ObservableName>
            <IsNone_Longitudinal>false</IsNone_Longitudinal>
            <IsNone_Lateral>false</IsNone_Lateral>
            <OptInitSpeed>10</OptInitSpeed>
            <OptDriverModel>0</OptDriverModel>
            <OptDriverAction>0</OptDriverAction>
            <OptDriverSpeedControl>0</OptDriverSpeedControl>
            <OptSteer>0</OptSteer>
            <OptDriverCharact>0</OptDriverCharact>
            <StartSpeedCtrlTime>0</StartSpeedCtrlTime>
            <StartBrakeTime>0</StartBrakeTime>
            <StartThrottleTime>0</StartThrottleTime>
            <StartClutchTime>0</StartClutchTime>
            <StartTransTime>0</StartTransTime>
            <StartGearTime>0</StartGearTime>
            <InitSpeed>10</InitSpeed>
            <HasNone>false</HasNone>
            <HasOpenLoop>true</HasOpenLoop>
            <HasCloseLoop>true</HasCloseLoop>
            <MinSpeed>0</MinSpeed>
            <MaxSteerAngle>900</MaxSteerAngle>
            <MaxSteerRate>1200</MaxSteerRate>
            <Preview>1</Preview>
            <SpeedKp>0.14</SpeedKp>
            <SpeedKi>0.16</SpeedKi>
            <TLagDm>0</TLagDm>
            <BrakePerfSC>0.1</BrakePerfSC>
            <BrakeFpdperfSC>0.1</BrakeFpdperfSC>
            <SpeedVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(km/h)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SpeedVsTime diffgr:id="SpeedVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Speed>10</Speed>
                    </SpeedVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsTime>
            <PreviewTable>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PreviewTable" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PreviewTable">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PreviewTable" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PreviewTable>
            <SteeringAngle>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringAngle" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringAngle">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Tiem(s)" type="xs:float" />
                              <xs:element name="SteeringWheelAngle" msdata:Caption="Steering Wheel Angle(deg)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringAngle" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <SteeringAngle diffgr:id="SteeringAngle1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <SteeringWheelAngle>0.1</SteeringWheelAngle>
                    </SteeringAngle>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringAngle>
            <SteeringTorque>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SteeringTorque" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SteeringTorque">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(m)" type="xs:float" />
                              <xs:element name="SteeringTorque" msdata:Caption="Steering Torque(N*m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SteeringTorque" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SteeringTorque>
            <Ltarg>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Ltarg" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Ltarg">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="LateralOffset" msdata:Caption="Lateral Offset(m)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Ltarg" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Ltarg diffgr:id="Ltarg1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Station>0</Station>
                      <LateralOffset>0</LateralOffset>
                    </Ltarg>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </Ltarg>
            <SpeedVsStation>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="SpeedVsStation" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="SpeedVsStation">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Station" msdata:Caption="Station(m)" type="xs:float" />
                              <xs:element name="Speed" msdata:Caption="Speed(m/s)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//SpeedVsStation" />
                      <xs:field xpath="Station" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </SpeedVsStation>
            <PedalForce>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="PedalForce" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="PedalForce">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="PedalForce" msdata:Caption="Pedal Force(N)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//PedalForce" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </PedalForce>
            <BrakePressure>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="BrakePressure" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="BrakePressure">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="BrakePressure" msdata:Caption="Brake Control Pressure(Master Cylider)(MPa)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//BrakePressure" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <BrakePressure diffgr:id="BrakePressure1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <BrakePressure>10</BrakePressure>
                    </BrakePressure>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0</ConstValue>
            </BrakePressure>
            <ThrottleVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ThrottleVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ThrottleVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Throttle" msdata:Caption="Throttle(0-1)(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ThrottleVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <ThrottleVsTime diffgr:id="ThrottleVsTime1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Throttle>0.5</Throttle>
                    </ThrottleVsTime>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>0.5</ConstValue>
            </ThrottleVsTime>
            <ClutchVsTime>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="ClutchVsTime" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="ClutchVsTime">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Clutch" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//ClutchVsTime" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </ClutchVsTime>
            <Modetr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Modetr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Modetr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Modetr" msdata:Caption="Modetr(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Modetr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
              </Table>
              <ConstValue>10</ConstValue>
            </Modetr>
            <Geartr>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name />
              <Owner />
              <ObservableName />
              <IsConstant>true</IsConstant>
              <Table>
                <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:MainDataTable="Geartr" msdata:UseCurrentLocale="true">
                    <xs:complexType>
                      <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Geartr">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Time" msdata:Caption="Time(s)" type="xs:float" />
                              <xs:element name="Geartr" msdata:Caption="Shift(-)" type="xs:float" minOccurs="0" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:choice>
                    </xs:complexType>
                    <xs:unique name="Constraint1" msdata:PrimaryKey="true">
                      <xs:selector xpath=".//Geartr" />
                      <xs:field xpath="Time" />
                    </xs:unique>
                  </xs:element>
                </xs:schema>
                <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
                  <DocumentElement>
                    <Geartr diffgr:id="Geartr1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                      <Time>0</Time>
                      <Geartr>10</Geartr>
                    </Geartr>
                  </DocumentElement>
                </diffgr:diffgram>
              </Table>
              <ConstValue>3</ConstValue>
            </Geartr>
            <Trajectory>
              <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
              <Name>31bf20a0-117a-45ba-8453-edb800b24b17</Name>
              <Owner />
              <ObservableName>Veh_1_2</ObservableName>
              <TrajectoryKeyInTrajectoryPos />
              <Trajectory>
                <TrajectoryPoint>
                  <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
                  <Name />
                  <Owner />
                  <ObservableName />
                  <X>79.2120743</X>
                  <Y>3.8053143</Y>
                  <Z>0.324</Z>
                </TrajectoryPoint>
              </Trajectory>
              <TrajectoryKeyPoints />
            </Trajectory>
            <PathPlanning>true</PathPlanning>
            <SpeedPlanning>true</SpeedPlanning>
          </DriverControl>
          <_WheelHeight3D>0.324</_WheelHeight3D>
          <VehicleVersion>3.0</VehicleVersion>
          <VehiclePath30>D:\InstallationPackages\PanoSim4.1_V2X_FAW_3724\Bin\PanoSim3.0\Experiment\Vehicle\Veh_1.veh</VehiclePath30>
          <CarResource>Vehicle/Car1</CarResource>
          <IsYawDependLane>true</IsYawDependLane>
          <ModelType>P_Model</ModelType>
          <HeadingAngleOffset>0</HeadingAngleOffset>
        </PanoTestVehicle>
      </Children>
    </PanoCategory>
    <PanoCategory>
      <_UID>9a764ad8-bc5a-4d2f-9938-98fc51b47e6a</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>9a764ad8-bc5a-4d2f-9938-98fc51b47e6a</UID>
      <Name>Traffic</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>true</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Traffic.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoStochasticTraffic>
          <_UID>1dbb0c48-1beb-4e21-a2eb-95b2aa9fbcd8</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>1dbb0c48-1beb-4e21-a2eb-95b2aa9fbcd8</UID>
          <Name>Normal</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\StochasticTraffic.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <ExpDir />
          <TrafficDensity>0.5</TrafficDensity>
          <TrafficEnable>false</TrafficEnable>
          <StepLength>0.05</StepLength>
          <TrafficVehicles />
          <Cautious>0</Cautious>
          <Common>0</Common>
          <Radical>0</Radical>
          <Car>0</Car>
          <Truck>0</Truck>
          <Bus>0</Bus>
          <CarStartSpeed>0</CarStartSpeed>
          <CarMaxSpeed>0</CarMaxSpeed>
          <TruckStartSpeed>0</TruckStartSpeed>
          <TruckMaxSpeed>0</TruckMaxSpeed>
          <BusStartSpeed>0</BusStartSpeed>
          <BusMaxSpeed>0</BusMaxSpeed>
        </PanoStochasticTraffic>
        <PanoCategory>
          <_UID>59d964c6-c13d-4c6e-afc6-8e0006f5a0d3</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>59d964c6-c13d-4c6e-afc6-8e0006f5a0d3</UID>
          <Name>Interfering Vehicles</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Interfering Vehicles.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoDisturbance>
          <_UID>2c51a376-1c28-4fd6-b7cb-6d761dd0befe</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>2c51a376-1c28-4fd6-b7cb-6d761dd0befe</UID>
          <Name>Disturbance</Name>
          <Enable>false</Enable>
          <Visible>false</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>false</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Disturbance.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
          <DisturbanceEnable>false</DisturbanceEnable>
          <DisturbanceModel>Cut-In</DisturbanceModel>
          <CutInDisturbanceStartsCondition>AtTime</CutInDisturbanceStartsCondition>
          <CutInAtTimeValue>10</CutInAtTimeValue>
          <CutInAtStationValue>10</CutInAtStationValue>
          <CutInAtSpeedValue>10</CutInAtSpeedValue>
          <CutInAtDistanceValue>10</CutInAtDistanceValue>
          <CutInDisturbanceLaneInit>LeftLane</CutInDisturbanceLaneInit>
          <CutInSpeedValue>10</CutInSpeedValue>
          <CutInAngleValue>10</CutInAngleValue>
          <CutInDisturbingObject>Sedan</CutInDisturbingObject>
          <CutInDisturbingObjectUnityResource>Vehicle/Car1</CutInDisturbingObjectUnityResource>
          <SpeedVariationDisturbanceStartsCondition>AtTime</SpeedVariationDisturbanceStartsCondition>
          <SpeedVariationAtTimeValue>10</SpeedVariationAtTimeValue>
          <SpeedVariationAtStationValue>10</SpeedVariationAtStationValue>
          <SpeedVariationAtSpeedValue>10</SpeedVariationAtSpeedValue>
          <SpeedVariationAtDistanceValue>10</SpeedVariationAtDistanceValue>
          <SpeedVariationSideDistanceValue>0</SpeedVariationSideDistanceValue>
          <SpeedVariationDisturbingObject>Sedan</SpeedVariationDisturbingObject>
          <SpeedVariationDisturbingObjectUnityResource>Vehicle/Car1</SpeedVariationDisturbingObjectUnityResource>
          <SpeedVariationTimeArray />
          <SpeedVariationSpeedArray />
          <PedestrianCrossingDisturbanceStartsCondition>AtTime</PedestrianCrossingDisturbanceStartsCondition>
          <PedestrianCrossingAtTimeValue>10</PedestrianCrossingAtTimeValue>
          <PedestrianCrossingAtStationValue>10</PedestrianCrossingAtStationValue>
          <PedestrianCrossingAtSpeedValue>10</PedestrianCrossingAtSpeedValue>
          <PedestrianCrossingAtFrontDistanceValue>10</PedestrianCrossingAtFrontDistanceValue>
          <PedestrianCrossingAtSideDistanceValue>1</PedestrianCrossingAtSideDistanceValue>
          <PedestrianCrossingCrossAngleValue>0</PedestrianCrossingCrossAngleValue>
          <PedestrianCrossingEnsureCollision>false</PedestrianCrossingEnsureCollision>
          <PedestrianCrossingDisturbingObject>Boywalk</PedestrianCrossingDisturbingObject>
          <PedestrianCrossingDisturbingObjectUnityResource>People/Boywalk</PedestrianCrossingDisturbingObjectUnityResource>
          <PedestrianCrossingTimeArray>
            <double>0</double>
            <double>10</double>
          </PedestrianCrossingTimeArray>
          <PedestrianCrossingSpeedArray>
            <double>5.4</double>
            <double>5.4</double>
          </PedestrianCrossingSpeedArray>
        </PanoDisturbance>
        <PanoCategory>
          <_UID>f6d40651-c155-4c6a-a243-37991fafd8e0</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>f6d40651-c155-4c6a-a243-37991fafd8e0</UID>
          <Name>Pedestrian</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Pedestrian.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>7cc8f10b-91b0-45ef-85f4-ab1537c39626</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>7cc8f10b-91b0-45ef-85f4-ab1537c39626</UID>
          <Name>AuxiliarySign</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\AuxiliarySign.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather>
      <_UID>aabf1b99-5d91-4103-843c-cfc360b894c0</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>aabf1b99-5d91-4103-843c-cfc360b894c0</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <WeatherTypeData>Sunny</WeatherTypeData>
      <wt_TimeOfDay>0.375</wt_TimeOfDay>
      <wt_CloudsValue>0.6</wt_CloudsValue>
      <wt_RainValue>0</wt_RainValue>
      <wt_SnowValue>0</wt_SnowValue>
      <wt_FogValue>0</wt_FogValue>
      <wt_Wetness>0</wt_Wetness>
      <wt_Snowness>0</wt_Snowness>
      <wt_Cracks>0</wt_Cracks>
      <wt_Dirtiness>0</wt_Dirtiness>
      <wt_Opacity>0</wt_Opacity>
    </PanoWeather>
    <PanoCategory>
      <_UID>bade1d4c-ce40-4c3b-89b1-f77bb1e238fc</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>bade1d4c-ce40-4c3b-89b1-f77bb1e238fc</UID>
      <Name>StaticOjbects</Name>
      <Enable>true</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\StaticOjbects.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Children>
        <PanoCategory>
          <_UID>c2c9fcf8-5268-4e72-9d42-34017533a310</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>c2c9fcf8-5268-4e72-9d42-34017533a310</UID>
          <Name>Traffic Signs</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Traffic Signs.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>3f640610-cce5-42d6-91cc-cbca039137a5</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>3f640610-cce5-42d6-91cc-cbca039137a5</UID>
          <Name>Facilities</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Facilities.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>9d7b7718-6fc5-49d5-9f33-a0413286ef79</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>9d7b7718-6fc5-49d5-9f33-a0413286ef79</UID>
          <Name>Buildings</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Buildings.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
        <PanoCategory>
          <_UID>da238c8f-f093-496a-bf8c-6bc0db14b17d</_UID>
          <Version>PanoObjects.dll Version 1.0.0.1</Version>
          <UID>da238c8f-f093-496a-bf8c-6bc0db14b17d</UID>
          <Name>Vegetations</Name>
          <Enable>true</Enable>
          <Visible>true</Visible>
          <IsDeletable>false</IsDeletable>
          <IsReadOny>true</IsReadOny>
          <IconRelativePathName>
            <uriKind>eRelativeDataPath</uriKind>
            <RelativePathName>\Vegetations.jpg</RelativePathName>
          </IconRelativePathName>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Roll>0</Roll>
          <Yaw>0</Yaw>
          <Pitch>0</Pitch>
          <Children />
        </PanoCategory>
      </Children>
    </PanoCategory>
    <PanoWeather2>
      <_UID>a9bb1b2a-7c54-4cb4-8b4b-098c0cb34df7</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>a9bb1b2a-7c54-4cb4-8b4b-098c0cb34df7</UID>
      <Name>Weather</Name>
      <Enable>false</Enable>
      <Visible>false</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\Weather2.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <_weatherContext>
        <WeatherType>Sunny</WeatherType>
        <RainyType>None</RainyType>
        <SnowyTypes>None</SnowyTypes>
        <FogVisibility>300</FogVisibility>
        <TimeOfDay>9</TimeOfDay>
        <LightPoles>true</LightPoles>
        <Cloudiness>0.5</Cloudiness>
      </_weatherContext>
      <WeatherType>Sunny</WeatherType>
      <RainyType>None</RainyType>
      <SnowyType>None</SnowyType>
      <FogVisibility>300</FogVisibility>
      <TimeOfDay>9</TimeOfDay>
      <LightPoles>true</LightPoles>
      <Cloudiness>0.5</Cloudiness>
    </PanoWeather2>
    <PanoV2X>
      <_UID>eb87bbf0-e2e9-4956-86c2-3e0778ba4b5f</_UID>
      <Version>PanoObjects.dll Version 1.0.0.1</Version>
      <UID>eb87bbf0-e2e9-4956-86c2-3e0778ba4b5f</UID>
      <Name>V2X</Name>
      <Enable>false</Enable>
      <Visible>true</Visible>
      <IsDeletable>false</IsDeletable>
      <IsReadOny>false</IsReadOny>
      <IconRelativePathName>
        <uriKind>eRelativeDataPath</uriKind>
        <RelativePathName>\V2X.jpg</RelativePathName>
      </IconRelativePathName>
      <X>0</X>
      <Y>0</Y>
      <Z>0</Z>
      <Roll>0</Roll>
      <Yaw>0</Yaw>
      <Pitch>0</Pitch>
      <Data>
        <ProductVersion>PanoDataVersion 1.0.0.0</ProductVersion>
        <Name>eb87bbf0-e2e9-4956-86c2-3e0778ba4b5f</Name>
        <Owner />
        <ObservableName>V2X</ObservableName>
        <NetModel>Ideal_Model</NetModel>
        <Scenario>HighWay</Scenario>
        <CommunicationRadius>500</CommunicationRadius>
        <DeliveryRatio>0.5</DeliveryRatio>
        <AverageDelay>50</AverageDelay>
        <PercentageInTraffic>100</PercentageInTraffic>
        <V2XParticipants>
          <SerializableDictionary>
            <key>
              <string>TrafficLight</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>IndicationSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>WarningSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>ForbiddenSign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>HighwaySign</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Facilities</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>SUMOVehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
          <SerializableDictionary>
            <key>
              <string>Vehicle</string>
            </key>
            <value>
              <boolean>false</boolean>
            </value>
          </SerializableDictionary>
        </V2XParticipants>
      </Data>
      <OBUModel>Ideal_Model</OBUModel>
      <Scenario>HighWay</Scenario>
      <CommunicationRadius>500</CommunicationRadius>
      <DeliveryRatio>0.5</DeliveryRatio>
      <AverageDelay>50</AverageDelay>
      <PercentageInTraffic>100</PercentageInTraffic>
    </PanoV2X>
  </Children>
  <StopTime>500</StopTime>
  <StartTime>0</StartTime>
  <ExpDir>D:\NewPanoSimData\Experiment\DNPW_a</ExpDir>
  <IsLinkToOtherExpModel>false</IsLinkToOtherExpModel>
  <MDLFullPath />
  <MDLDirectory />
  <MDLExpName />
  <NeedBuild>false</NeedBuild>
  <NeedDownload>false</NeedDownload>
</PanoExperiment>